### ISSUE TITLE
error handling ? 

### ISSUE THREAD

**Issue by shahmirzali49** [rei-codes/infinite-list-riverpod#1]
what's your method for showing the error widget? when an error happens it show like this:  https://gist.github.com/Roaa94/4e6febdfc732e70572b3fbd53cfeea4e?permalink_comment_id=4288281#gistcomment-4288281

OnGoingLoading and OnGoingError states.

examples : 
https://pub.dev/packages/infinite_scroll_pagination
https://www.freecodecamp.org/news/infinite-pagination-in-flutter-with-riverpod/

**Comment by rei-codes** [comment]
Actually, the way we approach is quite different here with package you mentioned

you can't handle the data as the same way as they do.

Let me explain.

In the package:
ListView sends a fetch request and waits for the data on every page
if error then show refresh button
if success then add to list and let user scroll down

page 1 – success
page 2 – success
page 3 – fail and stop (prevents scrolling down and let the user retry until the request succeeds)
page 4 – can’t send request until the error fixed

in this approach, you have to wait for the data. If you scroll too fast, you will be stuck at the loading state for a while, and it won’t be a seamless/smooth experience.(If the user has a fast internet connection, it will be a smooth experience tho. and most of the time they won't even encounter with the error/loading states at all)

On the other hand, in the example:
ListView sends a request to know the total length of the list at first. So ListView can know where to stop to prevent the range error.
if error then show refresh button (I’ll put a code sample below)
if success then display the data on the UI

page 1 – success
page 2 – fail (show refresh button)
page 3 – success (show the data below the error)
page 4 – fail (show refresh button)
page 5 – fail (show refresh button)
page 6 – success (show the data below the error)

as you can see in this example, if you scroll too fast, you don't have to wait for the data, you can just continue to scroll even if it fails or not, and you will get seamless/smooth experience.

But what if we get some errors on some pages that we passed, how can we handle the errors?
Actually, the answer is pretty simple! Riverpod gives us error state to handle the errors. we can basically put an error message and a refresh button to fix the problem.

I just updated the error state in the example and put 3 examples in it. You can just pick one as you wish.

```dart
class _ListItem extends ConsumerWidget {
  const _ListItem();

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final index = ref.read(listIndexProvider);
    final asyncData = ref.watch(catAtIndexProvider(index));
    return asyncData.when(
      data: (cat) => Card(child: ListTile(title: Text(cat.fact))),
      error: (_, __) {
        final page = index ~/ limit;
        final isFirstCard = index % limit == 0;
        // Show only the first error card and hide the others.
        if (!isFirstCard) return const SizedBox.shrink();
        return Card(
          child: ListTile(
            title: Text('Error! Page:$page, Index: $index'),
            trailing: OutlinedButton(
              child: const Text('Retry'),
              onPressed: () {
                // Refresh all pages
                // Even though it will use more network request.
                // UI will only rebuild the problematic widgets.
                ref.invalidate(paginatedCatsProvider);

                // Refresh only the current page
                ref.invalidate(paginatedCatsProvider(page));

                // Refresh all the problematic pages til the current page
                for (var i = 0; i <= page; i++) {
                  final hasError = ref.read(paginatedCatsProvider(i)).hasError;
                  if (hasError) {
                    ref.invalidate(paginatedCatsProvider(i));
                  }
                }
              },
            ),
          ),
        );
      },
      loading: () => const Card(child: ListTile()),
    );
  }
}
```


I hope my answer helped you to understand.

Takeaway: Both of them are correct and great, and just pick one that depends on your needs.

**Comment by shahmirzali49** [comment]
@rei-codes thanks for your reply, I understand what you explained. 

but Don't you think this is a bad UI/UX ? I mean success data items then error items and then again success data :) 



https://github.com/rei-codes/infinite-list-riverpod/assets/49102327/216b338b-5a73-45d8-ae3a-1384d5414098

**Comment by rei-codes** [comment]
Yes, it has a worse UX in terms of error handling than the other approach, but it is not common to get errors. I believe that you won't encounter that much.

You can also add some additional steps to improve the UX.
For example, you can retry the fetch request when it fails. (using retry interceptors or something else). this way, you can decrease the chance to show the error message to the user.
and, If It's a connectivity problem, you can listen to connection changes and refresh them automatically when the connection is back, etc.

**Comment by shahmirzali49** [comment]
Okay thank you for you suggestions.
